### ISSUE TITLE
Doxygen files are missing in project 10, 11, 12

### ISSUE THREAD

**Issue by rioj7** [franneck94/UdemyCmake#1]
The file `docs/Doxyfile` is missing in project 10, 11, 12

What is the use of the `configure_file()` call if you don't have variables in the `Doxyfile`

The file is present in `FinalCmake/docs/Doxyfile` but contains a typo for the `INPUT` property

```
INPUT                  =    ../src \
INPUT                       ../include
```

```
INPUT                  =    ../src ../include
```

**Comment by franneck94** [comment]
Added the files.

And this was no typo, mine version works like yours.
